### ISSUE TITLE
Missing guidance on setting up the content model

### ISSUE THREAD

**Issue by petrsvihlik** [kentico-michaelb/kontent-mvc-navigation#1]
hey Mike, I wanted to give it a go today but...how can I test it? there is no information regarding setting up the content model nor an export from the backup manager...I could check the code but I'd like to see it in action first.

(or you could share your project id at least :))

**Comment by petrsvihlik** [comment]
+ any reason to have WaitForLoadingNewContent in the appconfig?

**Comment by kentico-michaelb** [comment]
I will share the config in a private message for testing. I am currently working on creating an export, but there are some obstacles regarding the languages that come with the Dancing Goat sample project and importing to a fresh Kontent project.

As for "WaitForLoadingNewContent" option, there isn't a reason at this part of the series, so I will remove it.
